// ==========================================
// EVERY-TOOL - HOOFDSCRIPT MET DEFINITIEVE TAALFIX
// ==========================================

const translations = {
  nl: {
    placeholder: "Plak hier je tekst...",
    menuHeader: "Kies een Tool",
    menuHome: "🏠 Overzicht / Home",
    menuTimer: "⏱️ Speech & Presentatie",
    menuChecker: "✍️ Grammatica Bot",
    menuAi: "🤖 AI-Tekst Detector",
    menuTts: "🔊 Tekst-naar-Spraak",
    menuTranslate: "🌍 Vertaal Tool",
    menuQr: "📱 QR Code Generator",
    menuConverter: "🔄 Universele Converter",
    menuBlog: "📰 Blog",
    blogTitle: "10 handige gratis online tools voor studenten en contentmakers",
    blogIntro: "Op zoek naar handige online tools zonder ingewikkelde installatie of abonnement? Ontdek 10 gratis toepassingen die je helpen met school, schrijven en content maken.",
    blogBackBtn: "← Terug naar overzicht",
    langTitle: "Taal / Language:",
    shareBtn: "🔗 Deel",
    heroTag: "Meet Every-Tool",
    homeHeading: "Slimme tools voor al je tekst en spraak",
    homeSub: "Optimaliseer je presentaties, controleer op spelfouten of analyseer zinsstructuren in een handomdraai. Snel, veilig en betrouwbaar.",
    searchPlaceholder: "Typ om een tool te zoeken...",
    searchBtn: "Zoeken",
    aboutTitle: "💡 Over Every-Tool & Onze Functionaliteiten",
    aboutText: "Alle berekeningen vinden direct plaats in je eigen webbrowser (client-side), wat maximale privacy garandeert. Geen van je teksten wordt opgeslagen op externe servers.",
    faqTitle: "❓ Veelgestelde Vragen (FAQ)",
    faq1Q: "Hoe werkt de Speech Timer?",
    faq1A: "Plak je presentatietekst in de tool om direct je spreektijd te berekenen op basis van verschillende snelheden.",
    faq2Q: "Worden mijn teksten opgeslagen?",
    faq2A: "Nee, alle verwerking gebeurt lokaal in je browser. Dankzij LocalStorage onthoudt je browser wel tijdelijk je invoer.",
    faq3Q: "Is het gebruik van Every-Tool gratis?",
    faq3A: "Ja, alle tools op dit platform zijn volledig gratis te gebruiken voor studenten, professionals en contentmakers.",
    faq4Q: "Hoe betrouwbaar is de AI-Tekst Detector?",
    faq4A: "De AI-detector kijkt naar statistische kenmerken zoals zinslengte en variatie in schrijfstijl.",
    faq5Q: "Kan ik de gegenereerde audio downloaden?",
    faq5A: "Ja, in de Tekst-naar-Spraak tool kun je direct na het invoeren klikken om het audiobestand (.WAV) op te slaan.",
    faq6Q: "Moet ik software installeren om deze tools te gebruiken?",
    faq6A: "Nee, absoluut niet. Every-Tool werkt volledig web-based in elke moderne browser.",
    faq7Q: "Hoe werkt de Grammatica Bot?",
    faq7A: "De Grammatica Bot maakt gebruik van de LanguageTool API om automatisch je tekst te scannen op spelfouten.",
    t1Title: "Speech & Presentatie Timer",
    t1Sub: "Bereken direct hoe lang jouw tekst duurt om voor te lezen.",
    slow: "🐢 Langzaam",
    norm: "🚶 Normaal",
    fast: "🐇 Snel",
    practice: "Oefen je speech live:",
    startBtn: "Start",
    pauseBtn: "Pauze",
    resumeBtn: "Hervat",
    resetBtn: "Reset",
    t2Title: "Grammatica & Spelfout Bot",
    t2Sub: "Controleer automatisch op spelfouten via LanguageTool.",
    t2Issues: "Gevonden Aandachtspunten:",
    btnClean: "✨ Automatisch Herstellen",
    btnCopy: "📋 Kopiëren",
    clearText: "🗑️ Wis tekst",
    copyAlert: "Gekopieerd naar klembord!",
    noText: "Geen tekst ingevoerd.",
    noIssues: "✅ Geen spelfouten gevonden!",
    checkingText: "⏳ Bezig met controleren...",
    apiError: "⚠️ Verbindingsfout met LanguageTool API.",
    t3Title: "AI-Tekst Detector Indicator",
    t3Sub: "Analyseer zinsstructuur op AI-kenmerken.",
    t3Score: "Geschatte AI-waarschijnlijkheid",
    aiShort: "Voer minimaal 50 tekens in voor een schatting.",
    aiHigh: "Hoge mate van regelmatige zinsopbouw gedetecteerd.",
    aiLow: "Natuurlijke variatie in zinslengte gedetecteerd.",
    ttsTitle: "Tekst-naar-Spraak",
    ttsSub: "Laat je tekst direct voorlezen of download de audio als bestand.",
    ttsLabelLang: "Spraak Taal:",
    speakBtn: "🔊 Lees Hardop",
    downloadAudioBtn: "📥 Download Audio (.WAV)",
    stopSpeechBtn: "⏹️ Stop",
    ttsStatusPlaceholder: "Status: Klaar om voor te lezen of te downloaden...",
    ttsSpeaking: "🔊 Bezig met voorlezen...",
    ttsDone: "✅ Voorlezen voltooid.",
    ttsStopped: "⏹ Gestopt.",
    ttsDownloaded: "📥 Audiobestand succesvol gedownload!",
    ttsNoTextAlert: "Voer eerst wat tekst in!",
    ttsNoAudioTextAlert: "Voer eerst tekst in om te kunnen downloaden.",
    ttsNotSupported: "Je browser ondersteunt geen tekst-naar-spraak.",
    translateTitle: "Vertaal Tool",
    translateSub: "Vertaal je teksten snel naar verschillende talen.",
    translateLabelLang: "Kies doeltaal:",
    translateBtn: "🌍 Vertaal Tekst",
    translatePreviewPlaceholder: "Vertaalde tekst verschijnt hier...",
    translateAlert: "Vul alstublieft tekst in om te vertalen.",
    translatingText: "⏳ Bezig met vertalen...",
    translateError: "⚠️ Verbindingsfout met de vertaal API.",
    qrTitle: "QR Code Generator",
    qrSub: "Voer een URL in om direct een QR-code te genereren.",
    qrPlaceholder: "Vul een URL in...",
    qrGenBtn: "Genereer",
    downloadQR: "📥 Download QR-code",
    convTitle: "Universele Converter",
    convSub: "Converteer foto's, documenten of data eenvoudig naar een ander bestandsformaat.",
    convLabelFrom: "Wat wil je converteren?",
    convLabelTo: "Waar naartoe converteren?",
    convActionBtn: "Start Conversie",
    convStatus: "Selecteer een bestand en klik op start...",
    convAlert: "Selecteer eerst een bestand!",
    convLoading: "⏳ Bezig met omzetten...",
    convSuccess: "✅ Succesvol omgezet naar",
    convError: "❌ Er is iets misgegaan tijdens de conversie.",
    optNl: "🇳🇱 Nederlands",
    optEn: "🇬🇧 Engels",
    optDe: "🇩🇪 Duits",
    optFr: "🇫🇷 Frans",
    optEs: "🇪🇸 Spaans",
    optHeic: "📷 HEIC Afbeelding (Apple)",
    optImg: "🖼️ Standaard Afbeelding (PNG/JPG/WebP)",
    optTxt: "📄 Tekstbestand (.txt)",
    optJpg: "🖼 JPG Afbeelding",
    optPng: "🖼️ PNG Afbeelding",
    optWebp: "🌐 WebP Afbeelding",
    adSpace: "Advertentie Ruimte (Google AdSense)",
    sec1: "256-bit SSL-beveiliging",
    sec2: "100% Privacy - Lokale verwerking",
    sec3: "Direct resultaat",
    speeds: { slow: 90, norm: 100, fast: 125 },
    pageTitles: {
      home: "Every-Tool | Gratis Online Handige Tools & Conversie",
      timer: "Speech & Presentatie Timer | Every-Tool",
      checker: "Grammatica & Spelfout Bot | Every-Tool",
      ai: "AI-Tekst Detector Indicator | Every-Tool",
      tts: "Tekst-naar-Spraak Generator | Every-Tool",
      translate: "Gratis Online Vertaal Tool | Every-Tool",
      qr: "Gratis QR Code Generator | Every-Tool",
      converter: "Universele Bestandsconverter | Every-Tool",
      blog: "Blog & Artikelen | Every-Tool"
    }
  },

  de: {
    placeholder: "Fügen Sie Ihren Text hier ein...",
    menuHeader: "Werkzeug wählen",
    menuHome: "🏠 Übersicht / Home",
    menuTimer: "⏱️ Rede & Präsentation",
    menuChecker: "✍️ Grammatik Bot",
    menuAi: "🤖 AI-Text-Detektor",
    menuTts: "🔊 Text-to-Speech",
    menuTranslate: "🌍 Übersetzung",
    menuQr: "📱 QR Code Generator",
    menuConverter: "🔄 Universeller Konverter",
    menuBlog: "📰 Blog",
    blogTitle: "10 nützliche kostenlose Online-Tools für Studenten und Creator",
    blogIntro: "Auf der Suche nach praktischen Online-Tools ohne Installation? Entdecken Sie 10 kostenlose Anwendungen für Schule, Schreiben und Content-Erstellung.",
    blogBackBtn: "← Zurück zur Übersicht",
    langTitle: "Sprache / Language:",
    shareBtn: "🔗 Teilen",
    heroTag: "Meet Every-Tool",
    homeHeading: "Intelligente Tools für Text und Präsentationen",
    homeSub: "Optimieren Sie Ihre Präsentationen, prüfen Sie Rechtschreibung oder analysieren Sie Satzstrukturen im Handumdrehen.",
    searchPlaceholder: "Nach einem Tool suchen...",
    searchBtn: "Suchen",
    aboutTitle: "💡 Über Every-Tool & Funktionen",
    aboutText: "Alle Berechnungen finden direkt in Ihrem Browser (client-side) statt, was maximale Privatsphäre garantiert.",
    faqTitle: "❓ Häufig gestellte Fragen (FAQ)",
    faq1Q: "Wie funktioniert der Speech Timer?",
    faq1A: "Fügen Sie Ihren Text ein, um die Sprechdauer basierend auf verschiedenen Geschwindigkeiten zu berechnen.",
    faq2Q: "Werden meine Texte gespeichert?",
    faq2A: "Nein, die gesamte Verarbeitung erfolgt lokal in Ihrem Browser.",
    faq3Q: "Ist Every-Tool kostenlos?",
    faq3A: "Ja, alle Tools auf dieser Plattform sind völlig kostenlos nutzbar.",
    faq4Q: "Wie zuverlässig ist der AI-Text-Detektor?",
    faq4A: "Der Detektor prüft statistische Merkmale. Es ist eine Schätzung und kein 100%iger Beweis.",
    faq5Q: "Kann ich die Audio-Datei herunterladen?",
    faq5A: "Ja, Sie können die generierte Audio-Datei als .WAV direkt herunterladen.",
    faq6Q: "Muss ich Software installieren?",
    faq6A: "Nein, alles läuft direkt im Browser.",
    faq7Q: "Wie funktioniert der Grammatik-Bot?",
    faq7A: "Er nutzt die LanguageTool API zur automatischen Fehlerprüfung.",
    t1Title: "Rede & Präsentations-Timer",
    t1Sub: "Berechnen Sie sofort die Sprechdauer.",
    slow: "🐢 Langsam",
    norm: "🚶 Normal",
    fast: "🐇 Schnell",
    practice: "Üben Sie live:",
    startBtn: "Start",
    pauseBtn: "Pause",
    resumeBtn: "Fortsetzen",
    resetBtn: "Zurücksetzen",
    t2Title: "Grammatik & Rechtschreibung",
    t2Sub: "Automatische Prüfung via LanguageTool.",
    t2Issues: "Gefundene Probleme:",
    btnClean: "✨ Korrigieren",
    btnCopy: "📋 Kopieren",
    clearText: "🗑️ Text löschen",
    copyAlert: "Kopiert!",
    noText: "Kein Text.",
    noIssues: "✅ Keine Fehler gefunden!",
    checkingText: "⏳ Überprüfung läuft...",
    apiError: "⚠️ Verbindungsfehler mit der LanguageTool API.",
    t3Title: "AI-Text-Detektor",
    t3Sub: "Analysieren Sie die Satzstruktur.",
    t3Score: "Geschätzte KI-Wahrscheinlichkeit",
    aiShort: "Mindestens 50 Zeichen eingeben.",
    aiHigh: "Hohe Regelmäßigkeit.",
    aiLow: "Natürliche Variation.",
    ttsTitle: "Text-to-Speech",
    ttsSub: "Lassen Sie Ihren Text vorlesen oder als Audiodatei herunterladen.",
    ttsLabelLang: "Sprachauswahl:",
    speakBtn: "🔊 Vorlesen",
    downloadAudioBtn: "📥 Audio herunterladen",
    stopSpeechBtn: "⏹️ Stopp",
    ttsStatusPlaceholder: "Status: Bereit...",
    ttsSpeaking: "🔊 Wiedergabe läuft...",
    ttsDone: "✅ Wiedergabe beendet.",
    ttsStopped: "⏹️ Gestoppt.",
    ttsDownloaded: "📥 Audiodatei erfolgreich heruntergeladen!",
    ttsNoTextAlert: "Bitte geben Sie zuerst Text ein!",
    ttsNoAudioTextAlert: "Bitte geben Sie Text zum Herunterladen ein.",
    ttsNotSupported: "Ihr Browser unterstützt Text-to-Speech nicht.",
    translateTitle: "Übersetzungstool",
    translateSub: "Übersetzen Sie Ihre Texte in verschiedene Sprachen.",
    translateLabelLang: "Zielsprache wählen:",
    translateBtn: "🌍 Text übersetzen",
    translatePreviewPlaceholder: "Übersetzter Text erscheint hier...",
    translateAlert: "Bitte geben Sie Text zum Übersetzen ein.",
    translatingText: "⏳ Übersetzung läuft...",
    translateError: "⚠️ Verbindungsfehler mit der Übersetzungs-API.",
    qrTitle: "QR Code Generator",
    qrSub: "Geben Sie eine URL ein, um sofort einen QR-Code zu generieren.",
    qrPlaceholder: "Geben Sie eine URL ein...",
    qrGenBtn: "Generieren",
    downloadQR: "📥 QR-Code herunterladen",
    convTitle: "Universeller Konverter",
    convSub: "Konvertieren Sie Fotos, Dokumente oder Daten einfach in ein anderes Format.",
    convLabelFrom: "Was möchten Sie konvertieren?",
    convLabelTo: "Wohin konvertieren?",
    convActionBtn: "Konvertierung starten",
    convStatus: "Wählen Sie eine Datei aus und klicken Sie auf Start...",
    convAlert: "Bitte wählen Sie zuerst eine Datei aus!",
    convLoading: "⏳ Konvertierung läuft...",
    convSuccess: "✅ Erfolgreich konvertiert nach",
    convError: "❌ Bei der Konvertierung ist ein Fehler aufgetreten.",
    optNl: "🇳🇱 Niederländisch",
    optEn: "🇬🇧 Englisch",
    optDe: "🇩🇪 Deutsch",
    optFr: "🇫🇷 Französisch",
    optEs: "🇪🇸 Spanisch",
    optHeic: "📷 HEIC Bild (Apple)",
    optImg: "🖼️ Standard Bild (PNG/JPG/WebP)",
    optTxt: "📄 Textdatei (.txt)",
    optJpg: "🖼️ JPG Bild",
    optPng: "🖼️ PNG Bild",
    optWebp: "🌐 WebP Bild",
    adSpace: "Werbeplatz (Google AdSense)",
    sec1: "256-bit SSL-Sicherheit",
    sec2: "100% Datenschutz - Lokale Verarbeitung",
    sec3: "Sofortiges Ergebnis",
    speeds: { slow: 110, norm: 130, fast: 160 },
    pageTitles: {
      home: "Every-Tool | Nützliche Online-Tools & Konvertierung",
      timer: "Rede & Präsentations-Timer | Every-Tool",
      checker: "Grammatik & Rechtschreibung Bot | Every-Tool",
      ai: "KI-Text-Detektor | Every-Tool",
      tts: "Text-to-Speech Generator | Every-Tool",
      translate: "Kostenloses Übersetzungstool | Every-Tool",
      qr: "Kostenloser QR-Code-Generator | Every-Tool",
      converter: "Universeller Dateikonverter | Every-Tool",
      blog: "Blog & Artikel | Every-Tool"
    }
  },

  en: {
    placeholder: "Paste your text here...",
    menuHeader: "Select Tool",
    menuHome: "🏠 Overview / Home",
    menuTimer: "⏱ Speech & Presentation",
    menuChecker: "✍️ Grammar Bot",
    menuAi: "🤖 AI Text Detector",
    menuTts: "🔊 Text-to-Speech",
